spring:
  application:
    name: scheduling-service

  jackson:
    mapper:
      accept-case-insensitive-enums: true

  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/pulse_care_scheduling
    driverClassName: org.postgresql.Driver
    username: pulsecare
    password: pulsecare

  # JPA / Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # RabbitMQ Configuration 
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  # GraphQL Configuration 
  graphql:
    graphiql:
      enabled: true
    schema:
      locations: classpath:graphql/

server:
  port: 8081

rabbitmq:
  queue:
    appointment: appointment-queue
  exchange:
    appointment: appointment-exchange
  routing:
    key:
      appointment: appointment.created

# JWT Configuration 
api:
  security:
    token:
      secret: pulse-care-secret-key
